// flow-typed signature: 6a15c8b81740132a2153f16febf87ec3
// flow-typed version: <<STUB>>/@slack/client_v^3.10.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slack/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slack/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slack/client/examples/example-incoming-webhook' {
  declare module.exports: any;
}

declare module '@slack/client/examples/example-rtm-client-datastore' {
  declare module.exports: any;
}

declare module '@slack/client/examples/example-rtm-client' {
  declare module.exports: any;
}

declare module '@slack/client/examples/example-web-client' {
  declare module.exports: any;
}

declare module '@slack/client/examples/upload-a-file' {
  declare module.exports: any;
}

declare module '@slack/client/jsdoc' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/client' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/default/legacy-rtm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/errors' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/events/client' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/events/index' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/events/rtm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/events/utils' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/incoming-webhook/client' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/retry-policies' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/rtm/client' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/transports/call-transport' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/transports/request' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/transports/ws' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/client' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/api' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/auth' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/bots' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/channels' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/chat' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/dnd' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/emoji' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/files.comments' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/files' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/groups' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/im' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/index' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/mpim' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/oauth' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/pins' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/presence' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/reactions' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/reminders' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/rtm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/search' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/stars' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/team' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/usergroups' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/usergroups.users' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/users' {
  declare module.exports: any;
}

declare module '@slack/client/lib/clients/web/facets/users.profile' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/data-store' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/index' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/memory-data-store' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/base-channel' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/bots' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/channels' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/dm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/groups' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/index' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/message' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/presence' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/reactions' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/stars' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/team' {
  declare module.exports: any;
}

declare module '@slack/client/lib/data-store/message-handlers/user' {
  declare module.exports: any;
}

declare module '@slack/client/lib/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/base-channel' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/channel-group' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/channel' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/dm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/file' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/group' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/index' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/model' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/mpdm' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/property-type' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/user-group' {
  declare module.exports: any;
}

declare module '@slack/client/lib/models/user' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/events/utils' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/incoming-webhook/client' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/rtm/connection-logic' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/rtm/retry-policy' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/rtm/send-message' {
  declare module.exports: any;
}

declare module '@slack/client/test/clients/web/client' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/data-store' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/memory-data-store' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/bot' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/channel-group-dm' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/message' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/presence' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/raw' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/reaction' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/team' {
  declare module.exports: any;
}

declare module '@slack/client/test/data-store/message-handlers/user' {
  declare module.exports: any;
}

declare module '@slack/client/test/fixtures/index' {
  declare module.exports: any;
}

declare module '@slack/client/test/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/test/models/helpers' {
  declare module.exports: any;
}

declare module '@slack/client/test/models/model' {
  declare module.exports: any;
}

declare module '@slack/client/test/utils/client' {
  declare module.exports: any;
}

declare module '@slack/client/test/utils/mock-ws-server' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slack/client/examples/example-incoming-webhook.js' {
  declare module.exports: $Exports<'@slack/client/examples/example-incoming-webhook'>;
}
declare module '@slack/client/examples/example-rtm-client-datastore.js' {
  declare module.exports: $Exports<'@slack/client/examples/example-rtm-client-datastore'>;
}
declare module '@slack/client/examples/example-rtm-client.js' {
  declare module.exports: $Exports<'@slack/client/examples/example-rtm-client'>;
}
declare module '@slack/client/examples/example-web-client.js' {
  declare module.exports: $Exports<'@slack/client/examples/example-web-client'>;
}
declare module '@slack/client/examples/upload-a-file.js' {
  declare module.exports: $Exports<'@slack/client/examples/upload-a-file'>;
}
declare module '@slack/client/index' {
  declare module.exports: $Exports<'@slack/client'>;
}
declare module '@slack/client/index.js' {
  declare module.exports: $Exports<'@slack/client'>;
}
declare module '@slack/client/jsdoc.js' {
  declare module.exports: $Exports<'@slack/client/jsdoc'>;
}
declare module '@slack/client/lib/clients/client.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/client'>;
}
declare module '@slack/client/lib/clients/default/legacy-rtm.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/default/legacy-rtm'>;
}
declare module '@slack/client/lib/clients/errors.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/errors'>;
}
declare module '@slack/client/lib/clients/events/client.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/events/client'>;
}
declare module '@slack/client/lib/clients/events/index.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/events/index'>;
}
declare module '@slack/client/lib/clients/events/rtm.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/events/rtm'>;
}
declare module '@slack/client/lib/clients/events/utils.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/events/utils'>;
}
declare module '@slack/client/lib/clients/helpers.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/helpers'>;
}
declare module '@slack/client/lib/clients/incoming-webhook/client.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/incoming-webhook/client'>;
}
declare module '@slack/client/lib/clients/retry-policies.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/retry-policies'>;
}
declare module '@slack/client/lib/clients/rtm/client.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/rtm/client'>;
}
declare module '@slack/client/lib/clients/transports/call-transport.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/transports/call-transport'>;
}
declare module '@slack/client/lib/clients/transports/request.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/transports/request'>;
}
declare module '@slack/client/lib/clients/transports/ws.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/transports/ws'>;
}
declare module '@slack/client/lib/clients/web/client.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/client'>;
}
declare module '@slack/client/lib/clients/web/facets/api.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/api'>;
}
declare module '@slack/client/lib/clients/web/facets/auth.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/auth'>;
}
declare module '@slack/client/lib/clients/web/facets/bots.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/bots'>;
}
declare module '@slack/client/lib/clients/web/facets/channels.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/channels'>;
}
declare module '@slack/client/lib/clients/web/facets/chat.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/chat'>;
}
declare module '@slack/client/lib/clients/web/facets/dnd.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/dnd'>;
}
declare module '@slack/client/lib/clients/web/facets/emoji.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/emoji'>;
}
declare module '@slack/client/lib/clients/web/facets/files.comments.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/files.comments'>;
}
declare module '@slack/client/lib/clients/web/facets/files.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/files'>;
}
declare module '@slack/client/lib/clients/web/facets/groups.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/groups'>;
}
declare module '@slack/client/lib/clients/web/facets/im.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/im'>;
}
declare module '@slack/client/lib/clients/web/facets/index.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/index'>;
}
declare module '@slack/client/lib/clients/web/facets/mpim.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/mpim'>;
}
declare module '@slack/client/lib/clients/web/facets/oauth.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/oauth'>;
}
declare module '@slack/client/lib/clients/web/facets/pins.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/pins'>;
}
declare module '@slack/client/lib/clients/web/facets/presence.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/presence'>;
}
declare module '@slack/client/lib/clients/web/facets/reactions.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/reactions'>;
}
declare module '@slack/client/lib/clients/web/facets/reminders.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/reminders'>;
}
declare module '@slack/client/lib/clients/web/facets/rtm.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/rtm'>;
}
declare module '@slack/client/lib/clients/web/facets/search.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/search'>;
}
declare module '@slack/client/lib/clients/web/facets/stars.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/stars'>;
}
declare module '@slack/client/lib/clients/web/facets/team.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/team'>;
}
declare module '@slack/client/lib/clients/web/facets/usergroups.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/usergroups'>;
}
declare module '@slack/client/lib/clients/web/facets/usergroups.users.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/usergroups.users'>;
}
declare module '@slack/client/lib/clients/web/facets/users.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/users'>;
}
declare module '@slack/client/lib/clients/web/facets/users.profile.js' {
  declare module.exports: $Exports<'@slack/client/lib/clients/web/facets/users.profile'>;
}
declare module '@slack/client/lib/data-store/data-store.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/data-store'>;
}
declare module '@slack/client/lib/data-store/index.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/index'>;
}
declare module '@slack/client/lib/data-store/memory-data-store.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/memory-data-store'>;
}
declare module '@slack/client/lib/data-store/message-handlers/base-channel.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/base-channel'>;
}
declare module '@slack/client/lib/data-store/message-handlers/bots.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/bots'>;
}
declare module '@slack/client/lib/data-store/message-handlers/channels.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/channels'>;
}
declare module '@slack/client/lib/data-store/message-handlers/dm.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/dm'>;
}
declare module '@slack/client/lib/data-store/message-handlers/groups.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/groups'>;
}
declare module '@slack/client/lib/data-store/message-handlers/helpers.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/helpers'>;
}
declare module '@slack/client/lib/data-store/message-handlers/index.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/index'>;
}
declare module '@slack/client/lib/data-store/message-handlers/message.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/message'>;
}
declare module '@slack/client/lib/data-store/message-handlers/presence.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/presence'>;
}
declare module '@slack/client/lib/data-store/message-handlers/reactions.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/reactions'>;
}
declare module '@slack/client/lib/data-store/message-handlers/stars.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/stars'>;
}
declare module '@slack/client/lib/data-store/message-handlers/team.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/team'>;
}
declare module '@slack/client/lib/data-store/message-handlers/user.js' {
  declare module.exports: $Exports<'@slack/client/lib/data-store/message-handlers/user'>;
}
declare module '@slack/client/lib/helpers.js' {
  declare module.exports: $Exports<'@slack/client/lib/helpers'>;
}
declare module '@slack/client/lib/models/base-channel.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/base-channel'>;
}
declare module '@slack/client/lib/models/channel-group.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/channel-group'>;
}
declare module '@slack/client/lib/models/channel.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/channel'>;
}
declare module '@slack/client/lib/models/dm.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/dm'>;
}
declare module '@slack/client/lib/models/file.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/file'>;
}
declare module '@slack/client/lib/models/group.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/group'>;
}
declare module '@slack/client/lib/models/helpers.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/helpers'>;
}
declare module '@slack/client/lib/models/index.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/index'>;
}
declare module '@slack/client/lib/models/model.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/model'>;
}
declare module '@slack/client/lib/models/mpdm.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/mpdm'>;
}
declare module '@slack/client/lib/models/property-type.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/property-type'>;
}
declare module '@slack/client/lib/models/user-group.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/user-group'>;
}
declare module '@slack/client/lib/models/user.js' {
  declare module.exports: $Exports<'@slack/client/lib/models/user'>;
}
declare module '@slack/client/test/clients/events/utils.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/events/utils'>;
}
declare module '@slack/client/test/clients/helpers.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/helpers'>;
}
declare module '@slack/client/test/clients/incoming-webhook/client.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/incoming-webhook/client'>;
}
declare module '@slack/client/test/clients/rtm/connection-logic.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/rtm/connection-logic'>;
}
declare module '@slack/client/test/clients/rtm/retry-policy.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/rtm/retry-policy'>;
}
declare module '@slack/client/test/clients/rtm/send-message.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/rtm/send-message'>;
}
declare module '@slack/client/test/clients/web/client.js' {
  declare module.exports: $Exports<'@slack/client/test/clients/web/client'>;
}
declare module '@slack/client/test/data-store/data-store.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/data-store'>;
}
declare module '@slack/client/test/data-store/memory-data-store.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/memory-data-store'>;
}
declare module '@slack/client/test/data-store/message-handlers/bot.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/bot'>;
}
declare module '@slack/client/test/data-store/message-handlers/channel-group-dm.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/channel-group-dm'>;
}
declare module '@slack/client/test/data-store/message-handlers/message.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/message'>;
}
declare module '@slack/client/test/data-store/message-handlers/presence.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/presence'>;
}
declare module '@slack/client/test/data-store/message-handlers/raw.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/raw'>;
}
declare module '@slack/client/test/data-store/message-handlers/reaction.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/reaction'>;
}
declare module '@slack/client/test/data-store/message-handlers/team.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/team'>;
}
declare module '@slack/client/test/data-store/message-handlers/user.js' {
  declare module.exports: $Exports<'@slack/client/test/data-store/message-handlers/user'>;
}
declare module '@slack/client/test/fixtures/index.js' {
  declare module.exports: $Exports<'@slack/client/test/fixtures/index'>;
}
declare module '@slack/client/test/helpers.js' {
  declare module.exports: $Exports<'@slack/client/test/helpers'>;
}
declare module '@slack/client/test/models/helpers.js' {
  declare module.exports: $Exports<'@slack/client/test/models/helpers'>;
}
declare module '@slack/client/test/models/model.js' {
  declare module.exports: $Exports<'@slack/client/test/models/model'>;
}
declare module '@slack/client/test/utils/client.js' {
  declare module.exports: $Exports<'@slack/client/test/utils/client'>;
}
declare module '@slack/client/test/utils/mock-ws-server.js' {
  declare module.exports: $Exports<'@slack/client/test/utils/mock-ws-server'>;
}
